### ISSUE TITLE
drive.py can't move wheels

### ISSUE THREAD

**Issue by itamarwilf** [nanmu42/robo-playground#2]
I tried using your script for controlling a rooted robomaster s1 using the keyboard. The gimbal, video stream and blaster all worked but the "w s a d" controls were not workin and the wheels are not moving. do you have any idea why? Can it be caused by the root?

**Comment by nanmu42** [comment]
If gimbal and blaster work well, keyboard input should be taken care of correctly.

This is werid, is there something useful printed out in console?

You may try to connect and play with your device in a interactive Python console:

```py
>>> import robomasterpy as rm

# IP of RoboMaster is detected under router mode
>>> cmd = rm.Commander()

# check RoboMaster's API version
>>> cmd.version()
'version 00.00.00.60'

>>> cmd.get_robot_mode()
'chassis_lead'

# ensure your Robomaster has enough room to move
>>> cmd.chassis_move(x=-1, z=30)
'ok'
```

**Comment by itamarwilf** [comment]
Tried what you suggested, it only prints 'ok' but nothing happens..

**Comment by nanmu42** [comment]
> Tried what you suggested, it only prints 'ok' but nothing happens..

What is your ` cmd.version()` output?

**Comment by itamarwilf** [comment]
'version 00.00.00.60'

**Comment by nanmu42** [comment]
> 'version 00.00.00.60'

Perhaps there is some issue in your hardware.

Try official Robomaster python SDK, if it works, the issue is on RobomasterPy's side: https://robomaster-dev.readthedocs.io/en/latest/quick_start.html
